name: ci

on: [push]

jobs:
  package-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run package build
      run: script/cibuild-create-packages
  
  full-test-suite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt install -y virtualbox vagrant
    - name: Run test suite
      run: script/cibuild
